apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service9
    labels:
        name: config-service9
    namespace: default
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"grpc","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE9},"threads":1}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service9
    namespace: default
    labels: {}
spec:
    selector:
        matchLabels:
            app: service9
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service9
                version: ""
            annotations: {}
        spec:
            nodeName: worker10
            containers:
                - name: app
                  image: yizhengx/mucache:synthetic-pokerpp-0maxconn-grpc
                  imagePullPolicy: Always
                  env:
                    - name: APP_NAME
                      value: service
                    - name: CONF
                      value: /usr/src/emulator/config/conf.json
                    - name: GOMEMLIMIT
                      value: "1024000000"
                    - name: SLOWPOKE_DELAY_MICROS
                      value: "${SLOWPOKE_DELAY_MICROS_SERVICE9}"
                    - name: SLOWPOKE_PRERUN
                      value: "${SLOWPOKE_PRERUN}"
                    - name: SLOWPOKE_POKER_BATCH_THRESHOLD
                      value: "${SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE9}"
                    - name: SLOWPOKE_SERV_NAME
                      value: "service9"
                    - name: SLOWPOKE_IS_TARGET_SERVICE
                      value: "${SLOWPOKE_IS_TARGET_SERVICE_SERVICE9}"
                  ports:
                    - containerPort: 5000
                    - containerPort: 5550
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service9
---
apiVersion: v1
kind: Service
metadata:
    name: service9
    namespace: default
    labels: {}
    annotations:
        grpc: /
spec:
    selector:
        app: service9
    ports:
        - name: grpc
          port: 80
          targetPort: 5000
        - protocol: TCP
          port: 5550
          targetPort: 5550
          name: pokerpp
