kind: Service
apiVersion: v1
metadata:
  name: "reservation"
  labels:
    app: "reservation"
spec:
  selector:
    app: "reservation"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 5550
      targetPort: 5550
      name: zmq1
    - protocol: TCP
      port: 5551
      targetPort: 5551
      name: zmq2
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "reservation"
  labels:
    app: "reservation"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "reservation"
  template:
    metadata:
      labels:
        app: "reservation"
    spec:
      containers:
        - name: "reservation"
          image: yizhengx/mucache:hotel-all-flush-time-based-sleep
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          env:
            - name: APP_PORT
              value: "3000"
            - name: APP_NAME
              value: "reservation"
            - name: APP_NAME_NO_UNDERSCORES
              value: "reservation"
            - name: APP_NAMESPACE
              value: "hotel"
            - name: NODE_IDX
              value: "1"
            - name: CM_ENABLED
              value: "false"
            - name: EXPIRATION_TTL
              value: "0"
            - name: SLOWPOKE_DELAY_MICROS
              value: "${SLOWPOKE_DELAY_MICROS_RESERVATION}"
            - name: SLOWPOKE_PROCESSING_MICROS
              value: "${SLOWPOKE_PROCESSING_MICROS_RESERVATION}"
            - name: SLOWPOKE_PRERUN
              value: "${SLOWPOKE_PRERUN}"
            - name: SLOWPOKE_POKER_BATCH_THRESHOLD
              value: "${SLOWPOKE_POKER_BATCH_THRESHOLD_RESERVATION}"
          ports:
            - containerPort: 3000
            - containerPort: 5550
            - containerPort: 5551
          imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker4