cd $(dirname $0)

export PROCESSING_TIME_SERVICE0=0.00417584
export PROCESSING_TIME_SERVICE1=0.00380441
export PROCESSING_TIME_SERVICE2=0.00152958
export PROCESSING_TIME_SERVICE3=0.00291928
export PROCESSING_TIME_SERVICE4=0.00123996
export SLOWPOKE_DELAY_MICROS_SERVICE0=2479.5
export SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE0=100
export SLOWPOKE_IS_TARGET_SERVICE_SERVICE0=false
export SLOWPOKE_DELAY_MICROS_SERVICE1=2479.5
export SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE1=100
export SLOWPOKE_IS_TARGET_SERVICE_SERVICE1=false
export SLOWPOKE_DELAY_MICROS_SERVICE2=1239.5
export SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE2=100
export SLOWPOKE_IS_TARGET_SERVICE_SERVICE2=false
export SLOWPOKE_DELAY_MICROS_SERVICE3=2479.5
export SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE3=100
export SLOWPOKE_IS_TARGET_SERVICE_SERVICE3=false
export SLOWPOKE_DELAY_MICROS_SERVICE4=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE4=100
export SLOWPOKE_IS_TARGET_SERVICE_SERVICE4=true

# bash run.sh synthetic dag-cross-grpc-async 8 512 20000
for file in yamls/*
do
    envsubst < $file | kubectl delete -f -
    envsubst < $file | kubectl apply -f -
done