apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service7
    labels:
        name: config-service7
    namespace: default
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"http","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE7},"threads":1}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service7
    namespace: default
    labels: {}
spec:
    selector:
        matchLabels:
            app: service7
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service7
                version: ""
            annotations: {}
        spec:
            nodeName: worker2
            containers:
                - name: app
                  image: yizhengx/hydragen:fanout-w10-http-async
                  imagePullPolicy: Always
                  env:
                    - name: SERVICE_NAME
                      value: service7
                    - name: GOMEMLIMIT
                      value: "1024000000"
                    - name: SLOWPOKE_DELAY_MICROS
                      value: "${SLOWPOKE_DELAY_MICROS_SERVICE7}"
                    - name: SLOWPOKE_PRERUN
                      value: "${SLOWPOKE_PRERUN}"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 5
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 1000m
                        memory: 1024M
                    requests:
                        cpu: 1000m
                        memory: 512M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service7
---
apiVersion: v1
kind: Service
metadata:
    name: service7
    namespace: default
    labels: {}
    annotations:
        http: /
spec:
    selector:
        app: service7
    ports:
        - name: http
          port: 80
          targetPort: 5000
