apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service1
    labels:
        name: config-service1
    namespace: default
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"grpc","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE1},"threads":1},"network_complexity":{"forward_requests":"synchronous","response_payload_size":256,"called_services":[{"service":"service4","port":80,"endpoint":"endpoint1","protocol":"grpc","traffic_forward_ratio":1,"request_payload_size":512,"probability":0}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service1
    namespace: default
    labels: {}
spec:
    selector:
        matchLabels:
            app: service1
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service1
                version: ""
            annotations: {}
        spec:
            nodeName: worker2
            containers:
                - name: app
                  image: yizhengx/hydragen:dag-cross-grpc-sync
                  imagePullPolicy: Always
                  env:
                    - name: SERVICE_NAME
                      value: service1
                    - name: GOMEMLIMIT
                      value: "1024000000"
                    - name: SLOWPOKE_DELAY_MICROS
                      value: "${SLOWPOKE_DELAY_MICROS_SERVICE1}"
                    - name: SLOWPOKE_PRERUN
                      value: "${SLOWPOKE_PRERUN}"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    exec:
                        command: [/usr/bin/grpc_health_probe, '-addr=:5000']
                    initialDelaySeconds: 2
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 1000m
                        memory: 1024M
                    requests:
                        cpu: 1000m
                        memory: 512M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service1
---
apiVersion: v1
kind: Service
metadata:
    name: service1
    namespace: default
    labels: {}
    annotations:
        grpc: /
spec:
    selector:
        app: service1
    ports:
        - name: grpc
          port: 80
          targetPort: 5000
