apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service2
    labels:
        name: config-service2
    namespace: default
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"grpc","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE2},"threads":1},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":256,"called_services":[{"service":"service4","port":80,"endpoint":"endpoint1","protocol":"grpc","traffic_forward_ratio":1,"request_payload_size":512,"probability":0}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service2
    namespace: default
    labels: {}
spec:
    selector:
        matchLabels:
            app: service2
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service2
                version: ""
            annotations: {}
        spec:
            nodeName: worker3
            containers:
                - name: app
                  image: yizhengx/mucache:synthetic-pokerpp-0maxconn-grpc-debug
                  imagePullPolicy: Always
                  env:
                    - name: APP_NAME
                      value: service
                    - name: CONF
                      value: /usr/src/emulator/config/conf.json
                    - name: GOMEMLIMIT
                      value: "1024000000"
                    - name: SLOWPOKE_DELAY_MICROS
                      value: "${SLOWPOKE_DELAY_MICROS_SERVICE2}"
                    - name: SLOWPOKE_PRERUN
                      value: "${SLOWPOKE_PRERUN}"
                    - name: SLOWPOKE_POKER_BATCH_THRESHOLD
                      value: "${SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE2}"
                    - name: SLOWPOKE_SERV_NAME
                      value: "service2"
                    - name: SLOWPOKE_IS_TARGET_SERVICE
                      value: "${SLOWPOKE_IS_TARGET_SERVICE_SERVICE2}"
                  ports:
                    - containerPort: 5000
                    - containerPort: 5550
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service2
---
apiVersion: v1
kind: Service
metadata:
    name: service2
    namespace: default
    labels: {}
    annotations:
        grpc: /
spec:
    selector:
        app: service2
    ports:
        - name: grpc
          port: 80
          targetPort: 5000
        - protocol: TCP
          port: 5550
          targetPort: 5550
          name: pokerpp
