kind: Service
apiVersion: v1
metadata:
  name: "testtime"
  labels:
    app: "testtime"
spec:
  selector:
    app: "testtime"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: testtime
  labels:
    app: testtime
spec:
  containers:
  - name: command-container
    image: sleepymug/golang-timing-test-serv
    imagePullPolicy: Always
    command: ["./go-test", "{{kind}}", "{{num}}"]
    ports:
    - containerPort: 8000
    resources:
      limits:
        {{cpu}}
        memory: 4Gi
  restartPolicy: Never