cd $(dirname $0)

export SLOWPOKE_PROCESSING_MICROS_CART=1000
export SLOWPOKE_PROCESSING_MICROS_CHECKOUT=0
export SLOWPOKE_PROCESSING_MICROS_CURRENCY=0
export SLOWPOKE_PROCESSING_MICROS_EMAIL=0
export SLOWPOKE_PROCESSING_MICROS_FRONTEND=0
export SLOWPOKE_PROCESSING_MICROS_PAYMENT=0
export SLOWPOKE_PROCESSING_MICROS_PRODUCT_CATALOG=0
export SLOWPOKE_PROCESSING_MICROS_RECOMMENDATIONS=0
export SLOWPOKE_PROCESSING_MICROS_SHIPPING=0
export SLOWPOKE_DELAY_MICROS_CART=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_CART=100
export SLOWPOKE_IS_TARGET_SERVICE_CART=true
export SLOWPOKE_DELAY_MICROS_CHECKOUT=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_CHECKOUT=100
export SLOWPOKE_IS_TARGET_SERVICE_CHECKOUT=false
export SLOWPOKE_DELAY_MICROS_CURRENCY=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_CURRENCY=100
export SLOWPOKE_IS_TARGET_SERVICE_CURRENCY=false
export SLOWPOKE_DELAY_MICROS_EMAIL=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_EMAIL=100
export SLOWPOKE_IS_TARGET_SERVICE_EMAIL=false
export SLOWPOKE_DELAY_MICROS_FRONTEND=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_FRONTEND=100
export SLOWPOKE_IS_TARGET_SERVICE_FRONTEND=false
export SLOWPOKE_DELAY_MICROS_PAYMENT=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_PAYMENT=100
export SLOWPOKE_IS_TARGET_SERVICE_PAYMENT=false
export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_PRODUCT_CATALOG=100
export SLOWPOKE_IS_TARGET_SERVICE_PRODUCT_CATALOG=false
export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_RECOMMENDATIONS=100
export SLOWPOKE_IS_TARGET_SERVICE_RECOMMENDATIONS=false
export SLOWPOKE_DELAY_MICROS_SHIPPING=0.0
export SLOWPOKE_POKER_BATCH_THRESHOLD_SHIPPING=100
export SLOWPOKE_IS_TARGET_SERVICE_SHIPPING=false

DIR=/home/ubuntu/mucache/slowpoke/boutique-real-opt/results
for i in $(seq 1 10); do
    FILE=baseline-$i.log
    if [ ! -d "$DIR" ]; then
    mkdir -p $DIR
    fi
    if [ -f "$DIR/$FILE" ]; then
    echo "$DIR/$FILE exists."
    # exit 0
    continue
    fi
    env | grep SLOWPOKE > $DIR/$FILE
    bash /home/ubuntu/mucache/slowpoke/run.sh boutique mix 8 1024 100000 > $DIR/$FILE
done


