#!/bin/bash

cd $(dirname $0)

# export SLOWPOKE_DELAY_MICROS_CART=0
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
# export SLOWPOKE_DELAY_MICROS_CURRENCY=0
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=0
# export SLOWPOKE_DELAY_MICROS_PAYMENT=0
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=0
# export SLOWPOKE_PROCESSING_MICROS_CART=0
# export SLOWPOKE_PROCESSING_MICROS_CHECKOUT=0
# export SLOWPOKE_PROCESSING_MICROS_CURRENCY=0
# export SLOWPOKE_PROCESSING_MICROS_EMAIL=0
# export SLOWPOKE_PROCESSING_MICROS_FRONTEND=0
# export SLOWPOKE_PROCESSING_MICROS_PAYMENT=0
# export SLOWPOKE_PROCESSING_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_PROCESSING_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_PROCESSING_MICROS_SHIPPING=0
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_POKER_BATCH_THRESHOLD=40000000
# export SLOWPOKE_DELAY_MICROS_CART=0
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
# export SLOWPOKE_DELAY_MICROS_CURRENCY=0
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=0
# export SLOWPOKE_DELAY_MICROS_PAYMENT=0
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=0
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=287
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2543
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=129
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2543
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=213
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1271
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=229
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2034
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=103
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2034
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=170
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1017
# export SLOWPOKE_PRERUN=false

# export SLOWPOKE_PRERUN=true
# export SLOWPOKE_DELAY_MICROS_COMPOSEPOST=0
# export SLOWPOKE_DELAY_MICROS_SOCIALGRAPH=0
# export SLOWPOKE_DELAY_MICROS_HOMETIMELINE=0
# export SLOWPOKE_DELAY_MICROS_USERTIMELINE=0
# export SLOWPOKE_DELAY_MICROS_POSTSTORAGE=0

export SLOWPOKE_POKER_BATCH_THRESHOLD=40000000
export PROCESSING_TIME_SERVICE0=0.0
export PROCESSING_TIME_SERVICE1=0.0005
export PROCESSING_TIME_SERVICE2=0.0
export SLOWPOKE_DELAY_MICROS_SERVICE0=0.0
export SLOWPOKE_DELAY_MICROS_SERVICE1=0.0
export SLOWPOKE_DELAY_MICROS_SERVICE2=0.0
# export SLOWPOKE_PRERUN=true

env | grep "SLOWPOKE"
env | grep "PROCESSING"

benchmark=synthetic
request=chain-d2-http-sync
thread=8
conn=512
num_req=20000
# duration=${5:-10}

echo "bash run.sh $benchmark $request $thread $conn $num_req"
bash run.sh $benchmark $request $thread $conn $num_req
