#!/bin/bash

cd $(dirname $0)

export CLIENT_CPU_QUOTA=2

# export SLOWPOKE_DELAY_MICROS_CART=0
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
# export SLOWPOKE_DELAY_MICROS_CURRENCY=0
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=0
# export SLOWPOKE_DELAY_MICROS_PAYMENT=0
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=0
# export SLOWPOKE_PRERUN=false

# export SLOWPOKE_DELAY_MICROS_CART=287
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2543
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=129
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2543
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=213
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1271
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=229
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2034
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=103
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2034
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=170
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1017
# export SLOWPOKE_PRERUN=false

# export SLOWPOKE_PRERUN=true
# export SLOWPOKE_DELAY_MICROS_COMPOSEPOST=0
# export SLOWPOKE_DELAY_MICROS_SOCIALGRAPH=0
# export SLOWPOKE_DELAY_MICROS_HOMETIMELINE=0
# export SLOWPOKE_DELAY_MICROS_USERTIMELINE=0
# export SLOWPOKE_DELAY_MICROS_POSTSTORAGE=0

export PROCESSING_TIME_SERVICE0=0.0
export PROCESSING_TIME_SERVICE1=0.00081627
export PROCESSING_TIME_SERVICE2=0.00043233
export SLOWPOKE_DELAY_MICROS_SERVICE0=0
export SLOWPOKE_DELAY_MICROS_SERVICE1=0
export SLOWPOKE_DELAY_MICROS_SERVICE2=0

env | grep PROCESSING_TIME
env | grep SLOWPOKE_DELAY_MICROS

benchmark=syncthetic
request=${2:-fanout-w10-grpc-async}
thread=${3:-4}
conn=${4:-128}
# duration=${5:-10}

# bash run.sh $benchmark $request $thread $conn
# bash run-wrk2.sh $request $thread $conn $duration $rate
# bash run.sh $benchmark $request $thread $conn
# bash test.sh $benchmark $request $thread $conn
bash run.sh syncthetic chain-d2-grpc-sync 2 128 18000
