#!/bin/bash

cd $(dirname $0)

export SLOWPOKE_DELAY_MICROS_CART=0
export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
export SLOWPOKE_DELAY_MICROS_CURRENCY=0
export SLOWPOKE_DELAY_MICROS_EMAIL=0
export SLOWPOKE_DELAY_MICROS_FRONTEND=0
export SLOWPOKE_DELAY_MICROS_PAYMENT=0
export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
export SLOWPOKE_DELAY_MICROS_SHIPPING=0
export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=287
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2543
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=129
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2543
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=213
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1271
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=229
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2034
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=103
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2034
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=170
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1017
# export SLOWPOKE_PRERUN=false

# export SLOWPOKE_PRERUN=true
# export SLOWPOKE_DELAY_MICROS_COMPOSEPOST=0
# export SLOWPOKE_DELAY_MICROS_SOCIALGRAPH=0
# export SLOWPOKE_DELAY_MICROS_HOMETIMELINE=0
# export SLOWPOKE_DELAY_MICROS_USERTIMELINE=0
# export SLOWPOKE_DELAY_MICROS_POSTSTORAGE=0

benchmark=boutique
request=${2:-mix}
thread=${3:-4}
conn=${4:-128}
# duration=${5:-10}
for c in 500m 1000m 2000m 3000m; do
    find boutique/yamls/ -name '*.yaml' -exec sed -i "s/cpu: [0-9]*m/cpu: ${c}/g" {} +
    for d in 0 200 400 600; do
	for repeat in {1..10}; do 
	    export SLOWPOKE_DELAY_MICROS_FRONTEND=$d
	    bash run.sh $benchmark $request $thread $conn | tee results/diff-$c-$d-$repeat
	done
    done
done
# bash run-wrk2.sh $request $thread $conn $duration $rate
