#!/bin/bash

cd $(dirname $0)

export SLOWPOKE_PRERUN=false
export SLOWPOKE_POKER_BATCH_THRESHOLD=20000000
export SLOWPOKE_DELAY_MICROS_CASTINFO=0
export SLOWPOKE_DELAY_MICROS_COMPOSEREVIEW=0
export SLOWPOKE_DELAY_MICROS_FRONTEND=0
export SLOWPOKE_DELAY_MICROS_MOVIEID=0
export SLOWPOKE_DELAY_MICROS_MOVIEINFO=0
export SLOWPOKE_DELAY_MICROS_MOVIEREVIEWS=0
export SLOWPOKE_DELAY_MICROS_PAGE=0
export SLOWPOKE_DELAY_MICROS_PLOT=0
export SLOWPOKE_DELAY_MICROS_REVIEWSTORAGE=0
export SLOWPOKE_DELAY_MICROS_UNIQUEID=0
export SLOWPOKE_DELAY_MICROS_USER=0
export SLOWPOKE_DELAY_MICROS_USERREVIEWS=0
export SLOWPOKE_PROCESSING_MICROS_CASTINFO=0
export SLOWPOKE_PROCESSING_MICROS_COMPOSEREVIEW=0
export SLOWPOKE_PROCESSING_MICROS_FRONTEND=0
export SLOWPOKE_PROCESSING_MICROS_MOVIEID=0
export SLOWPOKE_PROCESSING_MICROS_MOVIEINFO=0
export SLOWPOKE_PROCESSING_MICROS_MOVIEREVIEWS=500
export SLOWPOKE_PROCESSING_MICROS_PAGE=0
export SLOWPOKE_PROCESSING_MICROS_PLOT=0
export SLOWPOKE_PROCESSING_MICROS_REVIEWSTORAGE=0
export SLOWPOKE_PROCESSING_MICROS_UNIQUEID=0
export SLOWPOKE_PROCESSING_MICROS_USER=0
export SLOWPOKE_PROCESSING_MICROS_USERREVIEWS=0


DIR=/home/ubuntu/mucache/slowpoke/movie/micro-debugging
mkdir -p $DIR

benchmark=movie
request=mix
thread=8
conn=512
num_req=50000
# FILE=service1-base.log
# FILE=combined_no_rlock-poker$threadshold.log
# FILE=s1_no_rlock-base.log
FILE=moviereviews500.log
if [[ -e $DIR/$FILE ]]; then
    echo "File $DIR/$FILE already exists. Skipping..."
    continue
fi
env | grep "SLOWPOKE" >$DIR/$FILE
env | grep "PROCESSING" >>$DIR/$FILE
echo "bash run.sh $benchmark $request $thread $conn $num_req" >>$DIR/$FILE
bash run.sh $benchmark $request $thread $conn $num_req >>$DIR/$FILE