kind: Service
apiVersion: v1
metadata:
  name: "${APP_NAME_NO_UNDERSCORES}"
  labels:
    app: "${APP_NAME_NO_UNDERSCORES}"
spec:
  selector:
    app: "${APP_NAME_NO_UNDERSCORES}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 5550
      targetPort: 5550
      name: zmq1
    - protocol: TCP
      port: 5551
      targetPort: 5551
      name: zmq2
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${APP_NAME_NO_UNDERSCORES}"
  labels:
    app: "${APP_NAME_NO_UNDERSCORES}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "${APP_NAME_NO_UNDERSCORES}"
  template:
    metadata:
      labels:
        app: "${APP_NAME_NO_UNDERSCORES}"
    spec:
      containers:
        - name: "${APP_NAME_NO_UNDERSCORES}"
          image: ${docker_io_username}/mucache:${application_namespace}-poker-time-spinning
          env:
            - name: APP_PORT
              value: "3000"
            - name: APP_NAME
              value: "${APP_NAME}"
            - name: APP_NAME_NO_UNDERSCORES
              value: "${APP_NAME_NO_UNDERSCORES}"
            - name: APP_NAMESPACE
              value: "${APP_NAMESPACE}"
            - name: NODE_IDX
              value: "${NODE_IDX}"
            - name: CM_ENABLED
              value: "${CM_ENABLED}"
            - name: EXPIRATION_TTL
              value: "${EXPIRATION_TTL}"
            - name: SLOWPOKE_DELAY_MICROS
              value: "${SLOWPOKE_DELAY_MICROS_${APP_NAME_NO_UNDERSCORES_UPPERCASE}}"
            - name: SLOWPOKE_PROCESSING_MICROS
              value: "${SLOWPOKE_PROCESSING_MICROS_${APP_NAME_NO_UNDERSCORES_UPPERCASE}}"
            - name: SLOWPOKE_PRERUN
              value: "${SLOWPOKE_PRERUN}"
            - name: SLOWPOKE_POKER_BATCH_THRESHOLD
              value: "${SLOWPOKE_POKER_BATCH_THRESHOLD}"
          ports:
            - containerPort: 3000
            - containerPort: 5550
            - containerPort: 5551
          imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker${NODE_IDX}