apiVersion: v1
kind: Pod
metadata:
  name: testtime
  labels:
    app: command-demo
spec:
  containers:
  - name: command-container
    image: sleepymug/golang-timing-test
    command: ["./go-test", "spinx", "1000"]
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
  restartPolicy: Never