apiVersion: v1
kind: Pod
metadata:
  name: testtime
  labels:
    app: command-demo
spec:
  containers:
  - name: command-container
    image: sleepymug/golang-timing-test
    command: ["./go-test", "{{kind}}", "{{num}}"]
    resources:
      limits:
        {{cpu}}
        memory: 4Gi
  restartPolicy: Never