apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service3
    labels:
        name: config-service3
    namespace: default
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"grpc","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE3},"threads":1},"network_complexity":{"forward_requests":"asynchronous","response_payload_size":256,"called_services":[{"service":"service5","port":80,"endpoint":"endpoint1","protocol":"grpc","traffic_forward_ratio":1,"request_payload_size":512,"probability":30},{"service":"service6","port":80,"endpoint":"endpoint1","protocol":"grpc","traffic_forward_ratio":1,"request_payload_size":512,"probability":70}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service3
    namespace: default
    labels: {}
spec:
    selector:
        matchLabels:
            app: service3
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service3
                version: ""
            annotations: {}
        spec:
            nodeName: worker1
            containers:
                - name: app
                  image: yizhengx/hydragen:dynamic-twice-grpc-async
                  imagePullPolicy: Always
                  env:
                    - name: SERVICE_NAME
                      value: service3
                    - name: GOMEMLIMIT
                      value: "1024000000"
                    - name: SLOWPOKE_DELAY_MICROS
                      value: "${SLOWPOKE_DELAY_MICROS_SERVICE3}"
                    - name: SLOWPOKE_PRERUN
                      value: "${SLOWPOKE_PRERUN}"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    exec:
                        command: [/usr/bin/grpc_health_probe, '-addr=:5000']
                    initialDelaySeconds: 2
                    periodSeconds: 1
                  resources:
                    limits:
                        cpu: 1000m
                        memory: 1024M
                    requests:
                        cpu: 1000m
                        memory: 512M
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service3
---
apiVersion: v1
kind: Service
metadata:
    name: service3
    namespace: default
    labels: {}
    annotations:
        grpc: /
spec:
    selector:
        app: service3
    ports:
        - name: grpc
          port: 80
          targetPort: 5000
