apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service5
    labels:
        name: config-service5
    namespace: default
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"http","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE5},"threads":1}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service5
    namespace: default
    labels: {}
spec:
    selector:
        matchLabels:
            app: service5
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service5
                version: ""
            annotations: {}
        spec:
            nodeName: worker6
            containers:
                - name: app
                  image: yizhengx/mucache:synthetic-all-flush-time-based-sleep
                  imagePullPolicy: Always
                  env:
                    - name: APP_NAME
                      value: service
                    - name: CONF
                      value: /usr/src/emulator/config/conf.json
                    - name: GOMEMLIMIT
                      value: "1024000000"
                    - name: SLOWPOKE_DELAY_MICROS
                      value: "${SLOWPOKE_DELAY_MICROS_SERVICE5}"
                    - name: SLOWPOKE_PRERUN
                      value: "${SLOWPOKE_PRERUN}"
                    - name: SLOWPOKE_POKER_BATCH_THRESHOLD
                      value: "${SLOWPOKE_POKER_BATCH_THRESHOLD_SERVICE5}"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 5
                    periodSeconds: 1
            volumes:
                - name: config-data-volume
                  configMap:
                    name: config-service5
---
apiVersion: v1
kind: Service
metadata:
    name: service5
    namespace: default
    labels: {}
    annotations:
        http: /
spec:
    selector:
        app: service5
    ports:
        - name: http
          port: 80
          targetPort: 5000
